
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Receivables Monitoring</title>
    <?php echo $__env->make('admin.reports.exports._styles', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
</head>
<body>

    <div class="pdf-header">
        <img src="<?php echo e(public_path('images/gledco-logo.png')); ?>" class="logo" alt="Gledco Logo">
        <div class="pdf-meta">
            <div style="font-weight:800; font-size:14px">GLEDCO SALES REPORT SYSTEM</div>
            <div>Division: <?php echo e($data['meta']['divisionName'] ?? 'All Divisions'); ?></div>
            <div>Report: Receivables | Date Range: <?php echo e($data['meta']['start'] ?? '—'); ?> to <?php echo e($data['meta']['end'] ?? '—'); ?></div>
            <div>Generated: <?php echo e($data['meta']['generated_at'] ?? now()->format('Y-m-d H:i')); ?></div>
        </div>
    </div>

    
    <div class="outer-box">
        <div class="section-title">Receivables Monitoring — Account Receivables</div>

        <table>
            <thead>
                <tr>
                    <th>#</th><th>Customer Name</th><th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php $__currentLoopData = $data['records']['account_receivables'] ?? []; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i => $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($i+1); ?></td>
                        <td><?php echo e($r['customer_name'] ?? ''); ?></td>
                        <td class="numeric"><?php echo e(number_format($r['amount'] ?? 0,2)); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                <?php for($x=0;$x<6;$x++): ?>
                    <tr><?php for($c=0;$c<3;$c++): ?><td>&nbsp;</td><?php endfor; ?></tr>
                <?php endfor; ?>
            </tbody>
        </table>
    </div>

    <div class="outer-box">
        <div class="section-title">Collection of Receivables</div>

        <table>
            <thead>
                <tr>
                    <th>#</th><th>Customer Name</th><th>Remarks</th><th>Check Details</th><th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php $__currentLoopData = $data['records']['collection_receivables'] ?? []; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i => $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($i+1); ?></td>
                        <td><?php echo e($r['customer_name'] ?? ''); ?></td>
                        <td><?php echo e($r['remarks'] ?? ''); ?></td>
                        <td><?php echo e($r['check_details'] ?? ''); ?></td>
                        <td class="numeric"><?php echo e(number_format($r['amount'] ?? 0,2)); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                <?php for($x=0;$x<6;$x++): ?>
                    <tr><?php for($c=0;$c<5;$c++): ?><td>&nbsp;</td><?php endfor; ?></tr>
                <?php endfor; ?>
            </tbody>
        </table>
    </div>

    

    <div class="pdf-footer">Generated by Gledco Sales Report System</div>
</body>
</html>
<?php /**PATH C:\xampp\htdocs\sales-report\resources\views\admin\reports\exports\receivables-pdf.blade.php ENDPATH**/ ?>