
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Borrowers Summary</title>
    <?php echo $__env->make('admin.reports.exports._styles', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
</head>
<body>

    <div class="pdf-header">
        <img src="<?php echo e(public_path('images/gledco-logo.png')); ?>" class="logo" alt="Gledco Logo">
        <div class="pdf-meta">
            <div style="font-weight:800; font-size:14px">GLEDCO SALES REPORT SYSTEM</div>
            <div>Division: <?php echo e($data['meta']['divisionName'] ?? 'All Divisions'); ?></div>
            <div>Report: Borrower's Agreement Monitoring</div>
            <div>Generated: <?php echo e($data['meta']['generated_at'] ?? now()->format('Y-m-d H:i')); ?></div>
        </div>
    </div>

    <div class="outer-box">
        <div class="section-title">Borrower's Agreement Monitoring</div>

        
        <table>
            <thead>
                <tr>
                    <th>Empties</th>
                    <th>Bodega Borrowed</th><th>Bodega Returned</th>
                    <th>CRS1 Borrowed</th><th>CRS1 Returned</th>
                    <th>CRS2 Borrowed</th><th>CRS2 Returned</th>
                    <th>CRS3 Borrowed</th><th>CRS3 Returned</th>
                    <th>Outside Town Borrowed</th><th>Outside Town Returned</th>
                    <th>Water Borrowed</th><th>Water Returned</th>
                </tr>
            </thead>
            <tbody>
                <?php $__currentLoopData = $data['records'] ?? []; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <tr>
                        <td><?php echo e($r['empties'] ?? ''); ?></td>
                        <td><?php echo e($r['bodega_borrowed'] ?? ''); ?></td>
                        <td><?php echo e($r['bodega_returned'] ?? ''); ?></td>

                        <td><?php echo e($r['crs1_borrowed'] ?? ''); ?></td>
                        <td><?php echo e($r['crs1_returned'] ?? ''); ?></td>

                        <td><?php echo e($r['crs2_borrowed'] ?? ''); ?></td>
                        <td><?php echo e($r['crs2_returned'] ?? ''); ?></td>

                        <td><?php echo e($r['crs3_borrowed'] ?? ''); ?></td>
                        <td><?php echo e($r['crs3_returned'] ?? ''); ?></td>

                        <td><?php echo e($r['outside_borrowed'] ?? ''); ?></td>
                        <td><?php echo e($r['outside_returned'] ?? ''); ?></td>

                        <td><?php echo e($r['water_borrowed'] ?? ''); ?></td>
                        <td><?php echo e($r['water_returned'] ?? ''); ?></td>
                    </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>

                
                <?php for($x=0;$x<6;$x++): ?>
                    <tr><?php for($c=0;$c<13;$c++): ?><td>&nbsp;</td><?php endfor; ?></tr>
                <?php endfor; ?>
            </tbody>
        </table>
    </div>

    <div class="pdf-footer">Generated by Gledco Sales Report System</div>

</body>
</html>
<?php /**PATH C:\xampp\htdocs\sales-report\resources\views\admin\reports\exports\borrowers-summary-pdf.blade.php ENDPATH**/ ?>