{{-- resources/views/admin/reports/exports/borrowers-summary-pdf.blade.php --}}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Borrowers Summary</title>
    @include('admin.reports.exports._styles')
</head>
<body>

    <div class="pdf-header">
        <img src="{{ public_path('images/gledco-logo.png') }}" class="logo" alt="Gledco Logo">
        <div class="pdf-meta">
            <div style="font-weight:800; font-size:14px">GLEDCO SALES REPORT SYSTEM</div>
            <div>Division: {{ $data['meta']['divisionName'] ?? 'All Divisions' }}</div>
            <div>Report: Borrower's Agreement Monitoring</div>
            <div>Generated: {{ $data['meta']['generated_at'] ?? now()->format('Y-m-d H:i') }}</div>
        </div>
    </div>

    <div class="outer-box">
        <div class="section-title">Borrower's Agreement Monitoring</div>

        {{-- This table will have many columns; because we use table-layout: fixed and nowrap with small font,
             columns will auto-shrink (option B). --}}
        <table>
            <thead>
                <tr>
                    <th>Empties</th>
                    <th>Bodega Borrowed</th><th>Bodega Returned</th>
                    <th>CRS1 Borrowed</th><th>CRS1 Returned</th>
                    <th>CRS2 Borrowed</th><th>CRS2 Returned</th>
                    <th>CRS3 Borrowed</th><th>CRS3 Returned</th>
                    <th>Outside Town Borrowed</th><th>Outside Town Returned</th>
                    <th>Water Borrowed</th><th>Water Returned</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['records'] ?? [] as $r)
                    <tr>
                        <td>{{ $r['empties'] ?? '' }}</td>
                        <td>{{ $r['bodega_borrowed'] ?? '' }}</td>
                        <td>{{ $r['bodega_returned'] ?? '' }}</td>

                        <td>{{ $r['crs1_borrowed'] ?? '' }}</td>
                        <td>{{ $r['crs1_returned'] ?? '' }}</td>

                        <td>{{ $r['crs2_borrowed'] ?? '' }}</td>
                        <td>{{ $r['crs2_returned'] ?? '' }}</td>

                        <td>{{ $r['crs3_borrowed'] ?? '' }}</td>
                        <td>{{ $r['crs3_returned'] ?? '' }}</td>

                        <td>{{ $r['outside_borrowed'] ?? '' }}</td>
                        <td>{{ $r['outside_returned'] ?? '' }}</td>

                        <td>{{ $r['water_borrowed'] ?? '' }}</td>
                        <td>{{ $r['water_returned'] ?? '' }}</td>
                    </tr>
                @endforeach

                {{-- blank rows to match layout --}}
                @for($x=0;$x<6;$x++)
                    <tr>@for($c=0;$c<13;$c++)<td>&nbsp;</td>@endfor</tr>
                @endfor
            </tbody>
        </table>
    </div>

    <div class="pdf-footer">Generated by Gledco Sales Report System</div>

</body>
</html>
