{{-- resources/views/admin/reports/exports/receivables-pdf.blade.php --}}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Receivables Monitoring</title>
    @include('admin.reports.exports._styles')
</head>
<body>

    <div class="pdf-header">
        <img src="{{ public_path('images/gledco-logo.png') }}" class="logo" alt="Gledco Logo">
        <div class="pdf-meta">
            <div style="font-weight:800; font-size:14px">GLEDCO SALES REPORT SYSTEM</div>
            <div>Division: {{ $data['meta']['divisionName'] ?? 'All Divisions' }}</div>
            <div>Report: Receivables | Date Range: {{ $data['meta']['start'] ?? '—' }} to {{ $data['meta']['end'] ?? '—' }}</div>
            <div>Generated: {{ $data['meta']['generated_at'] ?? now()->format('Y-m-d H:i') }}</div>
        </div>
    </div>

    {{-- For receivables we will render each section with same table style --}}
    <div class="outer-box">
        <div class="section-title">Receivables Monitoring — Account Receivables</div>

        <table>
            <thead>
                <tr>
                    <th>#</th><th>Customer Name</th><th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['records']['account_receivables'] ?? [] as $i => $r)
                    <tr>
                        <td>{{ $i+1 }}</td>
                        <td>{{ $r['customer_name'] ?? '' }}</td>
                        <td class="numeric">{{ number_format($r['amount'] ?? 0,2) }}</td>
                    </tr>
                @endforeach
                @for($x=0;$x<6;$x++)
                    <tr>@for($c=0;$c<3;$c++)<td>&nbsp;</td>@endfor</tr>
                @endfor
            </tbody>
        </table>
    </div>

    <div class="outer-box">
        <div class="section-title">Collection of Receivables</div>

        <table>
            <thead>
                <tr>
                    <th>#</th><th>Customer Name</th><th>Remarks</th><th>Check Details</th><th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['records']['collection_receivables'] ?? [] as $i => $r)
                    <tr>
                        <td>{{ $i+1 }}</td>
                        <td>{{ $r['customer_name'] ?? '' }}</td>
                        <td>{{ $r['remarks'] ?? '' }}</td>
                        <td>{{ $r['check_details'] ?? '' }}</td>
                        <td class="numeric">{{ number_format($r['amount'] ?? 0,2) }}</td>
                    </tr>
                @endforeach
                @for($x=0;$x<6;$x++)
                    <tr>@for($c=0;$c<5;$c++)<td>&nbsp;</td>@endfor</tr>
                @endfor
            </tbody>
        </table>
    </div>

    {{-- You can add other receivables sections as needed (stock transfer, shortage collections) using same style --}}

    <div class="pdf-footer">Generated by Gledco Sales Report System</div>
</body>
</html>
