{{-- resources/views/admin/reports/exports/remittance-pdf.blade.php --}}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Remittance Details PDF</title>
    @include('admin.reports.exports._styles')
</head>
<body>

    <div class="pdf-header">
        <img src="{{ public_path('images/gledco-logo.png') }}" class="logo" alt="Gledco Logo">
        <div class="pdf-meta">
            <div style="font-weight:800; font-size:14px">GLEDCO SALES REPORT SYSTEM</div>
            <div>Division: {{ $data['meta']['divisionName'] ?? 'All Divisions' }}</div>
            <div>Report: Remittance | Date Range: {{ $data['meta']['start'] ?? '—' }} to {{ $data['meta']['end'] ?? '—' }}</div>
            <div>Generated: {{ $data['meta']['generated_at'] ?? now()->format('Y-m-d H:i') }}</div>
        </div>
    </div>

    {{-- Outer box for remittance (checks table) --}}
    <div class="outer-box">
        <div class="section-title">Remittance Details — Check Payments</div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name of Bank</th>
                    <th>Account #</th>
                    <th>Account Name</th>
                    <th>Check Date</th>
                    <th>Remarks</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['records']['checks'] ?? [] as $i => $c)
                    <tr>
                        <td>{{ $i+1 }}</td>
                        <td>{{ $c['bank'] ?? '' }}</td>
                        <td>{{ $c['account_no'] ?? '' }}</td>
                        <td>{{ $c['account_name'] ?? '' }}</td>
                        <td>{{ $c['check_date'] ?? '' }}</td>
                        <td>{{ $c['remarks'] ?? '' }}</td>
                        <td class="numeric">{{ number_format($c['amount'] ?? 0,2) }}</td>
                    </tr>
                @endforeach

                {{-- fill blank rows to keep layout --}}
                @for($r=0;$r<8;$r++)
                    <tr>@for($c=0;$c<7;$c++)<td>&nbsp;</td>@endfor</tr>
                @endfor
            </tbody>
        </table>
    </div>

    {{-- Cash denominations / totals: side-by-side (keeps same visual style) --}}
    <div class="outer-box">
        <div class="section-title">Cash Details (Denominations) & Totals</div>

        <table>
            <thead>
                <tr>
                    <th>#</th><th>Denomination</th><th>PCS</th><th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['records']['denominations'] ?? [] as $i => $d)
                    <tr>
                        <td>{{ $i+1 }}</td>
                        <td class="numeric">{{ number_format($d['denomination'] ?? 0,2) }}</td>
                        <td class="numeric">{{ $d['pcs'] ?? '' }}</td>
                        <td class="numeric">{{ number_format($d['amount'] ?? 0,2) }}</td>
                    </tr>
                @endforeach

                {{-- blank rows to match design --}}
                @for($r=0;$r<6;$r++)
                    <tr>@for($c=0;$c<4;$c++)<td>&nbsp;</td>@endfor</tr>
                @endfor
            </tbody>
        </table>

        {{-- Totals row --}}
        <table style="margin-top:8px;">
            <tbody>
                <tr>
                    <td style="width:65%"></td>
                    <td style="width:35%">
                        <table style="width:100%">
                            <tr>
                                <td style="background:#fff;border:none;padding:6px">Total Cash & Checks</td>
                                <td class="numeric">{{ number_format($data['totals']['total_cash_checks'] ?? 0,2) }}</td>
                            </tr>
                            <tr>
                                <td style="background:#fff;border:none;padding:6px">Total Remitted</td>
                                <td class="numeric">{{ number_format($data['totals']['total_remit'] ?? 0,2) }}</td>
                            </tr>
                            <tr>
                                <td style="background:#fff;border:none;padding:6px">Overage/Shortage</td>
                                <td class="numeric">{{ number_format($data['totals']['shortage_overage'] ?? 0,2) }}</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>

    <div class="pdf-footer">Generated by Gledco Sales Report System</div>

</body>
</html>
